# General system configurations
system:
  log_level: "info"

# API related configurations
api:
  server:
    host: "127.0.0.1"
    port: 8080
  base_path: "/api"
  register_versions:
    - v1

# Faultdetector configurations
fault_detector:
  l1_rpc_endpoint: "https://rpc.notadegen.com/eth"
  l2_rpc_endpoint: "https://mainnet.optimism.io/"
  start_batch_index: 5901
  l2_output_oracle_contract_address: "0x0000000000000000000000000000000000000000"


# Slack notification service related configurations
slack:
  channel_id: "D06HM4LFMN1"
